version: '2.2'
services:
  es-node01:
    build: ./es
    # image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: es01
    ports:
      - "9200:9200"
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=false
      - cluster.initial_master_nodes=es01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./es/es01/data:/usr/share/elasticsearch/data:rw
      - ./es/es01/logs:/usr/share/elasticsearch/logs:rw
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kib01
    links:
      - "es-node01"
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge