FROM elasticsearch:7.9.2

ENV VERSION=7.9.2

# https://github.com/medcl/elasticsearch-analysis-ik/releases
# ADD https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v${VERSION}/elasticsearch-analysis-ik-$VERSION.zip /tmp/
COPY ./src/elasticsearch-analysis-ik-7.9.2.zip /tmp/
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install -b file:///tmp/elasticsearch-analysis-ik-$VERSION.zip

RUN rm -rf /tmp/*